apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mca-test-roy
type: Opaque
stringData:
  SPRING_POSTGRES_USERNAME: myapplication
  SPRING_POSTGRES_PASSWORD: M3P@ssw0rd!

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mca-test-roy
data:
  SPRING_POSTGRES_URL: jdbc:postgresql://my-db-test.io:5432/myapplication
